backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "lokaler"
    label: "lokaler"
    folder: "lokaler"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Eiendomsnavn", name: "title", widget: "string"}
      - {label: "Kort beskrivelse", name: "subtitle", widget: "string"}
      - {label: "Hovedbilde", name: "hovedbilde", widget: "image", required: false}
      - {label: "Om lokalene", name: "body", widget: "markdown"}
